version: 2
jobs:
  build:
    docker:
      - image: php:7.1-apache
    steps:
      - run:
          name: Install system packages
          command: apt-get update && apt-get -y install git
      - run:
          name: Install PHP extensions
          command: docker-php-ext-install pdo
      - checkout
      - run:
          name: Install Composer
          command: |
            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            php -r "if (hash_file('SHA384', 'composer-setup.php') === trim(file_get_contents('https://composer.github.io/installer.sig'))) { echo 'Installer verified'; } else { echo 'Installer invalid'; unlink('composer-setup.php'); } echo PHP_EOL;"
            php composer-setup.php
            php -r "unlink('composer-setup.php');"
      - run:
          name: Display PHP information
          command: |
            php -v
            php composer.phar --version
            php composer.phar update
      - run:
          name: Install project dependencies
          command: php composer.phar install
      - run:
          name: Check for runtime errors
          command: php -l wksalprogram.php
      - run:
          name: Check for unit errors
          command: vendor/bin/phpunit wksalprogram.php
      - run:
          name: Deploy Master to Heroku
          command: |
            git config --global user.email "vinyl1225@gmail.com"
            git config --global user.name "Caleb Priest"
            git add composer.lock
            git push --force https://heroku:94616200-b199-4200-bf43-05a6baa694a0@git.heroku.com/simple-salary-program.git master
